session_name: go-web
start_directory: ./ # load session relative to config location (project root).
windows:
- window_name: go-web
  focus: True
  layout: main-horizontal
  options:
    main-pane-height: 35
  panes:
  - focus: true
  - pane 
  - pane 
  - make watch_run
